### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Filter')

### ISSUE THREAD

**Issue by Lightmanticore** [GrooveypenguinX/Pack-n-Strap#4]
![image](https://github.com/GrooveypenguinX/Pack-n-Strap/assets/87406913/78e3821b-64d3-445e-9ca6-a54d3646f6d6)

**Comment by Lightmanticore** [comment]
So after using my brain and reading the actual page, I fixed it by moving above SVM. Thas my bad! Sorry king!

**Comment by GrooveypenguinX** [comment]
Lol all good!
